<template>
  <section id="faq" class="faq py-16">
    <div class="container mx-auto" data-aos="fade-up">
      <div class="flex flex-wrap">
        <!-- Content Section -->
        <div class="w-full lg:w-1/3 px-4 mb-8 lg:mb-0">
          <div class="px-xl-5">
            <h3 class="text-4xl font-normal mb-4">Frequently Asked <strong class="font-bold">Questions</strong></h3>
            <p class="text-lg text-gray-600">
              Find answers to common questions about our pest prediction system.
            </p>
          </div>
        </div>

        <!-- Accordion Section -->
        <div class="w-full lg:w-2/3 px-4">
          <div class="accordion" id="faqlist" data-aos="fade-up" data-aos-delay="100">
            <div v-for="(item, index) in faqs" :key="index" class="accordion-item border-0 mb-5 bg-white shadow-lg rounded-lg">
              <h3 class="accordion-header">
                <button
                  @click="toggle(index)"
                  :class="['accordion-button py-5 px-5 text-lg font-semibold rounded-lg', { 'text-teal-600': expandedIndex === index }]"
                >
                  <span class="text-xl pr-3">{{ index + 1 }}.</span>
                  {{ item.question }}
                </button>
              </h3>
              <div
                :id="'faq-content-' + (index + 1)"
                :class="['accordion-collapse transition-max-height ease-in-out duration-300', { 'max-h-0 overflow-hidden': expandedIndex !== index, 'max-h-screen': expandedIndex === index }]"
              >
                <div class="accordion-body p-5 text-gray-700">
                  {{ item.answer }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import {ref} from 'vue';

export default {
  name: 'FAQSection',
  setup() {
    const expandedIndex = ref(null);

    const faqs = [
      {
        question: 'How accurate is your pest prediction system?',
        answer: 'Our pest prediction system utilizes advanced algorithms and data analysis techniques to provide accurate forecasts. However, the accuracy may vary depending on various factors such as the quality of input data and environmental conditions.'
      },
      {
        question: 'Can I integrate your system with my existing pest control measures?',
        answer: 'Yes, our pest prediction system is designed to be compatible with various pest control measures. You can integrate it seamlessly into your existing workflow to enhance your pest management strategies.'
      },
      {
        question: 'How frequently is the system updated with new data?',
        answer: 'Our system is updated regularly with the latest data on pest populations, environmental conditions, and other relevant factors. This ensures that our predictions remain accurate and up-to-date.'
      },
      {
        question: 'Is technical support available for users?',
        answer: 'Yes, we provide technical support to our users to ensure smooth operation and effective utilization of our pest prediction system. Our support team is available to assist you with any queries or issues you may encounter.'
      },
      {
        question: 'How can I access the pest prediction reports?',
        answer: 'You can access the pest prediction reports through our user dashboard. Once logged in, you will have access to detailed reports, analysis, and insights generated by our system.'
      }
    ];

    const toggle = (index) => {
      expandedIndex.value = expandedIndex.value === index ? null : index;
    };

    return {
      faqs,
      expandedIndex,
      toggle
    };
  }
};
</script>

<style scoped>
.accordion-button {
  background-color: white; /* Tailwind default bg color */
  border: none; /* Tailwind border removal */
}

.accordion-body {
  background-color: white; /* Tailwind default bg color */
}

.accordion-collapse {
  transition: max-height 0.3s ease-in-out;
}
</style>
